### PR TITLE
Chore/migrate to esnext

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by TylerWasniowski** [comment]
This breaks the Hours File functionality.

**Comment by amilajack** [comment]
How does it break it? Share the stacktrace

**Comment by TylerWasniowski** [comment]
> How does it break it? Share the stacktrace

Any input produces the following error:

(node:23636) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at FormData._getContentDisposition (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\form-data\lib\form_data.js:226:40)
    at FormData._multiPartHeader (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\form-data\lib\form_data.js:177:33)
    at FormData.append (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\form-data\lib\form_data.js:70:21)
    at appendFormValue (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\request\request.js:326:21)
    at Request.require.Request.init (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\request\request.js:337:11)
    at Request.RP$initInterceptor [as init] (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\request-promise-core\configure\request2.js:45:29)
    at new Request (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\request\request.js:127:8)
    at request (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\request\index.js:53:10)
    at Object.getStaffHours (C:\Users\rooke\Projects\cosac-timecard-manager\lib\open-time-clock-requests.mjs:24:26)
    at getHours (C:\Users\rooke\Projects\cosac-timecard-manager\routes\data.mjs:32:51)
    at require.router.post (C:\Users\rooke\Projects\cosac-timecard-manager\routes\data.mjs:23:23)
    at Layer.handle [as handle_request] (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\rooke\Projects\cosac-timecard-manager\node_modules\express\lib\router\index.js:317:13)
(node:23636) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:23636) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by amilajack** [comment]
Now the issue is that `responses[1].find(entry => entry.ResourceKey === tutor.setmoreId)` returns undefined

**Comment by TylerWasniowski** [comment]
> Now the issue is that `responses[1].find(entry => entry.ResourceKey === tutor.setmoreId)` returns undefined

So it look like the root of the problem on my end is that all of the stuff you are trying to import from process.env doesn't exist. Is there something I have to change in my config so that the proper variables are exported to process.env?

If the imports work from process.env on your end, your issue might be that you don't have admin credentials on Setmore in your config.

**Comment by amilajack** [comment]
`cp .env.example .env`

**Comment by TylerWasniowski** [comment]
Sorry this took so long! Thanks for upgrading my repo! Also sorry you had to look at poop code XD

**Comment by amilajack** [comment]
Did the above commits fix it?

**Comment by TylerWasniowski** [comment]
Yes, I had to do `dotenv.config` before my imports because they loaded from process.env at import.

**Comment by amilajack** [comment]
Oh okay got it. Thanks for figuring this out. Lmk if you have any issues in the future. Glad to help out

**Comment by TylerWasniowski** [comment]
Thanks so much! I've learned a lot from you by proxy (Vikram has been channeling his knowledge into me that he says he got from you) haha

**Pull request merged**
